'use client';

import { useMemo, useState } from 'react';
import { ClipboardList, Ticket } from 'lucide-react';

type Order = { id: string; customer_name: string; customer_phone: string; order_type: 'delivery' | 'collection'; status: string; total: number; delivery_address: string | null; created_at: string };
type TicketSale = { id: string; event_id: string; customer_name: string; customer_email: string; quantity: number; status: string; created_at: string; event?: { title: string }[] | null };

export default function AdminOrders({ orders, ticketSales }: { orders: Order[]; ticketSales: TicketSale[] }) {
  const [view, setView] = useState<'orders' | 'tickets'>('orders');
  const ticketsSold = useMemo(() => ticketSales.filter((sale) => sale.status !== 'cancelled').reduce((total, sale) => total + sale.quantity, 0), [ticketSales]);
  return <section className="mt-10 border-t border-white/10 pt-10"><div className="grid gap-4 sm:grid-cols-3"><div className="border border-white/10 bg-charcoal/60 p-5"><ClipboardList className="h-5 w-5 text-gold" /><p className="mt-5 text-3xl font-black">{orders.length}</p><p className="text-sm text-white/50">Food orders</p></div><div className="border border-white/10 bg-charcoal/60 p-5"><Ticket className="h-5 w-5 text-gold" /><p className="mt-5 text-3xl font-black">{ticketsSold}</p><p className="text-sm text-white/50">Tickets sold/requested</p></div><div className="border border-white/10 bg-charcoal/60 p-5"><p className="text-3xl font-black">{orders.filter((order) => order.status !== 'delivered' && order.status !== 'cancelled').length}</p><p className="mt-5 text-sm text-white/50">Open food orders</p></div></div><div className="mt-8 flex gap-2 border-b border-white/10 pb-4"><button type="button" onClick={() => setView('orders')} className={`border px-4 py-2 text-sm font-bold ${view === 'orders' ? 'border-gold bg-gold text-black' : 'border-white/15 text-white/70'}`}>Food orders</button><button type="button" onClick={() => setView('tickets')} className={`border px-4 py-2 text-sm font-bold ${view === 'tickets' ? 'border-gold bg-gold text-black' : 'border-white/15 text-white/70'}`}>Ticket sales</button></div>{view === 'orders' ? <div className="grid gap-3">{orders.length ? orders.map((order) => <article key={order.id} className="border border-white/10 bg-charcoal/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">#{order.id.slice(0, 8)} · {order.customer_name}</h3><p className="mt-1 text-sm text-white/50">{order.order_type} · {order.status} · R{Number(order.total).toFixed(2)}</p></div><time className="text-xs text-white/40">{new Date(order.created_at).toLocaleString()}</time></div>{order.delivery_address && <p className="mt-3 text-sm text-white/65">Deliver to: {order.delivery_address}</p>}</article>) : <p className="border border-dashed border-white/15 p-8 text-center text-white/50">No food orders have been placed yet.</p>}</div> : <div className="grid gap-3">{ticketSales.length ? ticketSales.map((sale) => <article key={sale.id} className="border border-white/10 bg-charcoal/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{sale.event?.[0]?.title || 'Event'} · {sale.customer_name}</h3><p className="mt-1 text-sm text-white/50">{sale.quantity} ticket{sale.quantity === 1 ? '' : 's'} · {sale.status} · {sale.customer_email}</p></div><time className="text-xs text-white/40">{new Date(sale.created_at).toLocaleString()}</time></div></article>) : <p className="border border-dashed border-white/15 p-8 text-center text-white/50">No ticket sales have been recorded yet.</p>}</div>}</section>;
}
